-- Create company_cash_flow table
CREATE TABLE "company_cash_flow" (
  id SERIAL PRIMARY KEY,
  "cash_flows_from_operating_activities" numeric,
  "net_profit_before_tax_extraordinary_items" numeric,
  "profit_before_tax_from_continuing_operations" numeric,
  "profit_before_tax_from_discontinued_operations" numeric,
  "total_adjustments" numeric,
  "interest_income" numeric,
  "interest_expense" numeric,
  "dividend_income" numeric,
  "income_from_investments" numeric,
  "minority_interest" numeric,
  "finance_lease_rental_charges" numeric,
  "depreciation_and_amortization" numeric,
  "net_gain_on_lease_modification" numeric,
  "unrealised_and_realised_gain_loss" numeric,
  "impairment_gain_losses" numeric,
  "gain_loss_on_foreign_exchange" numeric,
  "gain_loss_on_sale_of_property_and_equipment" numeric,
  "profit_loss_on_sale_of_investments" numeric,
  "provision_and_write_off" numeric,
  "employee_stock_compensation_expenses" numeric,
  "share_of_profit_loss_of_joint_venture" numeric,
  "statutory_expenses" numeric,
  "other_adjustments" numeric,
  "operating_income_before_working_capital_changes" numeric,
  "increase_decrease_in_assets" numeric,
  "receivables" numeric,
  "non_current_receivables" numeric,
  "current_assets" numeric,
  "inventories" numeric,
  "loans_and_advances" numeric,
  "long_term_loans_and_advances" numeric,
  "investments" numeric,
  "long_term_investments" numeric,
  "net_stock_on_hire" numeric,
  "leased_assets_net_of_sale" numeric,
  "trade_bill_s_purchased" numeric,
  "land_and_development" numeric,
  "prepaid_expenses_and_other_current_assets" numeric,
  "other_current_assets" numeric,
  "other_non_current_assets" numeric,
  "increase_decrease_in_liabilities" numeric,
  "accounts_payable" numeric,
  "long_term_accounts_payable" numeric,
  "current_liabilities_and_provisions" numeric,
  "non_current_liabilities_and_provisions" numeric,
  "taxes_payable" numeric,
  "change_in_borrowing" numeric,
  "change_in_long_term_borrowing" numeric,
  "change_in_deposits" numeric,
  "change_in_long_term_deposits" numeric,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "co_code" integer,
  "month" integer,
  "quarter" integer,
  "year" integer
,  FOREIGN KEY ("co_code") REFERENCES "company_master" (co_code) ON UPDATE restrict ON DELETE restrict
);
ALTER TABLE "public"."company_cash_flow" add constraint "company_cash_flow_co_code_mqy" unique ("co_code", "month", "quarter", "year");
CREATE INDEX "idx_company_cash_flow_co_code" on "public"."company_cash_flow" using btree ("co_code");
CREATE INDEX "idx_company_cash_flow_month" on "public"."company_cash_flow" using btree ("month");
CREATE INDEX "idx_company_cash_flow_quarter" on "public"."company_cash_flow" using btree ("quarter");
CREATE INDEX "idx_company_cash_flow_year" on "public"."company_cash_flow" using btree ("year");
