-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mutual_fund" add column "mf_direct_variant_id" integer
--  null;
