-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_chat" add column "isFirst" boolean
--  not null default 'false';
