-- Create company_balance_sheet table
CREATE TABLE "company_balance_sheet" (
  id SERIAL PRIMARY KEY,
  "non_current_assets" numeric,
  "fixed_assets" numeric,
  "property_plant_and_equipments" numeric,
  "right_of_use_assets" numeric,
  "intangible_assets" numeric,
  "intangible_assets_under_development" numeric,
  "capital_work_in_progress" numeric,
  "non_current_investments" numeric,
  "investment_properties" numeric,
  "investments_in_subsidiaries_associates_and_joint_venture" numeric,
  "investments_of_life_insurance_business" numeric,
  "investments_long_term" numeric,
  "long_term_loans_and_advances" numeric,
  "other_non_current_assets" numeric,
  "long_term_loans_and_advances_and_other_non_current_assets" numeric,
  "biological_assets_other_than_bearer_plants_non_current" numeric,
  "loans_long_term" numeric,
  "others_financial_assets_long_term" numeric,
  "current_tax_assets_long_term" numeric,
  "insurance_related_assets_non_current" numeric,
  "other_non_current_assets_lt" numeric,
  "deferred_tax_assets" numeric,
  "total_non_current_assets" numeric,
  "current_assets" numeric,
  "inventories" numeric,
  "biological_assets_other_than_bearer_plants_current" numeric,
  "current_investments" numeric,
  "cash_and_cash_equivalents" numeric,
  "bank_balances_other_than_cash_and_cash_equivalents" numeric,
  "trade_receivables" numeric,
  "short_term_loans_and_advances" numeric,
  "other_current_assets" numeric,
  "short_term_loans_and_advances_and_other_current_assets" numeric,
  "loans_short_term" numeric,
  "others_financial_assets_short_term" numeric,
  "current_tax_assets_short_term" numeric,
  "insurance_related_assets_current" numeric,
  "other_current_assets_st" numeric,
  "assets_classified_as_held_for_sale" numeric,
  "total_current_assets" numeric,
  "total_assets" numeric,
  "current_liabilities" numeric,
  "short_term_borrowings" numeric,
  "lease_liabilities_current" numeric,
  "trade_payables" numeric,
  "other_current_liabilities" numeric,
  "others_financial_liabilities_short_term" numeric,
  "insurance_related_liabilities_current" numeric,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "co_code" integer,
  "month" integer,
  "quarter" integer,
  "year" integer
,  FOREIGN KEY ("co_code") REFERENCES "company_master" (co_code) ON UPDATE restrict ON DELETE restrict
);
ALTER TABLE "public"."company_balance_sheet" add constraint "company_balance_sheet_co_code_mqy" unique ("co_code", "month", "quarter", "year");
CREATE INDEX "idx_company_balance_sheet_co_code" on "public"."company_balance_sheet" using btree ("co_code");
CREATE INDEX "idx_company_balance_sheet_month" on "public"."company_balance_sheet" using btree ("month");
CREATE INDEX "idx_company_balance_sheet_quarter" on "public"."company_balance_sheet" using btree ("quarter");
CREATE INDEX "idx_company_balance_sheet_year" on "public"."company_balance_sheet" using btree ("year");
