version: 2
endpoint: http://localhost:8081
metadata_directory: metadata
admin_secret: r7XhNbY27yJ72em6CUSjfP66RymrHmoHDf3VGw0u8BbkeVeBCR227nAN3yhaM1qq
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:8080