-- Create company_deferred_tax table
CREATE TABLE "company_deferred_tax" (
  id SERIAL PRIMARY KEY,
  "created_at" timestamptz ,
  "updated_at" timestamptz ,
  "co_code" integer  not null,
  "yrc" integer ,
  "month" integer ,
  "quarter" integer ,
  "year" integer ,
  "aseg1" text ,
  "aval1" integer ,
  "aseg2" text ,
  "aval2" integer ,
  "aseg3" text ,
  "aval3" integer ,
  "aseg4" text ,
  "aval4" integer ,
  "aseg5" text ,
  "aval5" integer ,
  "aseg6" text ,
  "aval6" integer ,
  "aseg7" text ,
  "aval7" integer ,
  "aseg8" text ,
  "aval8" integer ,
  "aseg9" text ,
  "aval9" integer ,
  "aseg10" text ,
  "aval10" integer ,
  "aseg11" text ,
  "aval11" integer ,
  "aseg12" text ,
  "aval12" integer ,
  "aseg13" text ,
  "aval13" integer ,
  "aseg14" text ,
  "aval14" integer ,
  "aseg15" text ,
  "aval15" integer ,
  "aseg16" text ,
  "aval16" integer ,
  "aseg17" text ,
  "aval17" integer ,
  "aseg18" text ,
  "aval18" integer ,
  "aseg19" text ,
  "aval19" integer ,
  "aseg20" text ,
  "aval20" integer ,
  "lseg1" text ,
  "lval1" integer ,
  "lseg2" text ,
  "lval2" integer ,
  "lseg3" text ,
  "lval3" integer ,
  "lseg4" text ,
  "lval4" integer ,
  "lseg5" text ,
  "lval5" integer ,
  "lseg6" text ,
  "lval6" integer ,
  "lseg7" text ,
  "lval7" integer ,
  "lseg8" text ,
  "lval8" integer ,
  "lseg9" text ,
  "lval9" integer ,
  "lseg10" text ,
  "lval10" integer ,
  "lseg11" text ,
  "lval11" integer ,
  "lseg12" text ,
  "lval12" integer ,
  "lseg13" text ,
  "lval13" integer ,
  "lseg14" text ,
  "lval14" integer ,
  "lseg15" text ,
  "lval15" integer ,
  "lseg16" text ,
  "lval16" integer ,
  "lseg17" text ,
  "lval17" integer ,
  "lseg18" text ,
  "lval18" integer ,
  "lseg19" text ,
  "lval19" integer ,
  "lseg20" text ,
  "lval20" integer ,
  "atotal" integer ,
  "ltotal" integer ,
  "flag" text 
,  FOREIGN KEY ("co_code") REFERENCES "company_master" (co_code) ON UPDATE restrict ON DELETE restrict
);
ALTER TABLE "public"."company_deferred_tax" add constraint "u_company_deferred_tax" unique ("co_code", "yrc", "month", "quarter", "year", "flag");
CREATE INDEX "idx_company_deferred_tax_co_code" on "public"."company_deferred_tax" using btree ("co_code");
CREATE INDEX "idx_company_deferred_tax_yrc" on "public"."company_deferred_tax" using btree ("yrc");
CREATE INDEX "idx_company_deferred_tax_month" on "public"."company_deferred_tax" using btree ("month");
CREATE INDEX "idx_company_deferred_tax_quarter" on "public"."company_deferred_tax" using btree ("quarter");
CREATE INDEX "idx_company_deferred_tax_year" on "public"."company_deferred_tax" using btree ("year");
CREATE INDEX "idx_company_deferred_tax_flag" on "public"."company_deferred_tax" using btree ("flag");
