-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE VIEW latest_mutual_fund_holdings AS
-- SELECT
--     mutual_fund_id,
--     MAX(reporting_date) AS latest_reporting_date
-- FROM
--     mutual_fund_holdings
-- GROUP BY
--     mutual_fund_id;
