-- Create company_profile table
CREATE TABLE "company_profile" (
  id SERIAL PRIMARY KEY,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "lname" text,
  "isin" text,
  "hse_s_name" text,
  "inc_dt" text,
  "regadd1" text,
  "regadd2" text,
  "regdist" text,
  "regstate" text,
  "regpin" text,
  "tel1" text,
  "ind_l_name" text,
  "tel2" text,
  "fax1" text,
  "fax2" text,
  "auditor" text,
  "fv" integer,
  "mkt_lot" integer,
  "chairman" text,
  "co_sec" text,
  "co_code" integer,
  "email" text,
  "internet" text,
  "dir_name" text,
  "dir_desg" text,
  "co_code1" integer,
  "ho_add1" text,
  "ho_add2" text,
  "ho_add3" text,
  "ho_city" text,
  "ho_stcode" text,
  "ho_statename" text,
  "ho_pin" integer,
  "ho_tel1" text,
  "ho_tel2" integer,
  "ho_fax1" integer,
  "ho_fax2" integer,
  "ho_email" text,
  "ho_ctry_name" text,
  "co_code2" numeric,
  "co_add1" numeric,
  "co_add2" numeric,
  "co_add3" numeric,
  "co_city" numeric,
  "co_stcode" numeric,
  "co_statename" numeric,
  "co_pin" numeric,
  "co_tel1" numeric,
  "co_tel2" numeric,
  "co_fax1" numeric,
  "co_fax2" numeric,
  "co_email" numeric,
  "co_ctry_name" numeric,
  "co_code3" integer,
  "rcode" text,
  "reg_name" text,
  "reg_add1" text,
  "reg_add2" text,
  "reg_add3" text,
  "reg_add4" text,
  "reg_tel" text,
  "reg_fax" text,
  "reg_email" text,
  "reg_internet" text,
  "flag" text
,  FOREIGN KEY ("co_code") REFERENCES "company_master" (co_code) ON UPDATE restrict ON DELETE restrict
);
ALTER TABLE "public"."company_profile" add constraint "company_profile_co_code" unique ("co_code");
CREATE INDEX "idx_company_profile_co_code" on "public"."company_profile" using btree ("co_code");
