-- Create company_profit_and_loss table
CREATE TABLE "company_profit_and_loss" (
  id SERIAL PRIMARY KEY,
  "revenue_from_operations" numeric ,
  "sale_of_products" numeric ,
  "sale_of_services" numeric ,
  "income_from_investment_and_financial_services" numeric ,
  "income_from_insurance_operations" numeric ,
  "other_operating_revenue" numeric ,
  "less_excise_duty_gst" numeric ,
  "revenue_from_operations_net" numeric ,
  "other_income" numeric ,
  "total_revenue" numeric ,
  "changes_in_inventories" numeric ,
  "cost_of_material_consumed" numeric ,
  "internally_manufactured_intermediates_consumed" numeric ,
  "purchases_of_stock_in_trade" numeric ,
  "employee_benefits" numeric ,
  "total_other_expenses" numeric ,
  "manufacturing_operating_expenses" numeric ,
  "administrative_and_selling_expenses" numeric ,
  "other_expenses" numeric ,
  "finance_costs" numeric ,
  "depreciation_and_amortization" numeric ,
  "total_expenses" numeric ,
  "profit_before_exceptional_items_and_tax" numeric ,
  "exceptional_items_before_tax" numeric ,
  "profit_before_extraordinary_items_and_tax" numeric ,
  "extraordinary_items_before_tax" numeric ,
  "other_adjustments_before_tax" numeric ,
  "profit_before_tax" numeric ,
  "taxation" numeric ,
  "current_tax" numeric ,
  "mat_credit_entitlement" numeric ,
  "deferred_tax" numeric ,
  "other_tax" numeric ,
  "adjust_for_previous_year" numeric ,
  "profit_after_tax" numeric ,
  "extraordinary_items_after_tax" numeric ,
  "discontinued_operations_after_tax" numeric ,
  "profit_loss_from_discontinuing_operations" numeric ,
  "tax_expenses_of_discontinuing_operations" numeric ,
  "profit_attributable_to_shareholders" numeric ,
  "adjustments_to_net_income" numeric ,
  "preference_dividend" numeric ,
  "profit_attributable_to_equity_shareholders" numeric ,
  "earning_per_share_basic" numeric ,
  "earning_per_share_diluted" numeric ,
  "operation_profit_before_depreciation" numeric ,
  "operating_profit_after_depreciation" numeric ,
  "dividend_per_share" numeric ,
  "dividend_percentage" numeric ,
  "equity_dividend" numeric ,
  "created_at" timestamptz ,
  "updated_at" timestamptz ,
  "co_code" integer ,
  "month" integer ,
  "quarter" integer ,
  "year" integer ,
  FOREIGN KEY ("co_code") REFERENCES "company_master" (co_code) ON UPDATE restrict ON DELETE restrict
);
CREATE INDEX "company_profit_and_loss_co_code_index" on "public"."company_profit_and_loss" using btree ("co_code");
