version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ui/dipsip-vuetify/dist:/usr/share/nginx/html
      - /home/ec2-user/app/dipsip/certs/www:/var/www/certbot
      - /home/ec2-user/app/dipsip/certs/conf:/etc/letsencrypt
    depends_on:
      -api:
        condition: service_healthy
  certbot:
    image: certbot/certbot
    volumes:
      - /home/ec2-user/app/dipsip/certs/conf:/etc/letsencrypt
      - /home/ec2-user/app/dipsip/certs/www:/var/www/certbot
      - /var/log/letsencrypt:/var/log/letsencrypt  
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  graphql-engine:
    container_name: graphql
    build:
      dockerfile: Dockerfile
      context: ./server/hasura
      args:
        - POSTGRES_URL=$POSTGRES_URL
        - HASURA_ADMIN_SECRET=$HASURA_ADMIN_SECRET
    ports:
    - "8081:8080"
    restart: always
  api:
    build:
      context: ./server/middle
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3000/health"]
      interval: 5s       # Check every 5 seconds
      retries: 5         # Retry up to 5 times
      start_period: 10s  # Wait 10s before first check
      timeout: 5s        # Fail if no response in 5s  
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://51.158.62.147:11434
      #- OLLAMA_URL=http://ollama:11434
    volumes:
      - ./.env:/.env
      - ${DATA_ROOT_FOLDER:-/home/ec2-user/data}:/app/data
  pdf-to-text:
    build:
      context: ./server/pdf_to_text
      dockerfile: Dockerfile
    container_name: pdf-to-text
    ports:
      - "3500:3500"
    volumes:
      - ${NSE_ANNOUNCEMENTS_FROM_PDF:-/home/ec2-user/data/nse_announcements}:/app/input
      - ${NSE_ANNOUNCEMENTS_TO_TEXT:-/home/ec2-user/data/nse_announcements}:/app/output
    environment:
      - PORT=3500
      - HOST=0.0.0.0
    restart: unless-stopped
  #ollama:
  #  image: ollama/ollama
  #  ports:
  #    - "11434:11434"
  #  volumes:
  #    - ${OLLAMA_MODELS:-/home/ec2-user/data/ollama/ollama_models}:/root/.ollama/models
  #sqlite-web:
  #  image: coleifer/sqlite-web
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ${SQLITE_DB:-/home/ec2-user/data/sqlite_db}:/data
  #  environment:
  #    - SQLITE_DATABASE=/data/dipsip.db  # Replace 'your_database.db' with your actual database filename
  #    - SQLITE_WEB_PASSWORD=dipsip_password       # Optional: set a password for basic authentication
  #    - SQLITE_WEB_USERNAME=admin_dipsip              # Optional: set a username for basic authentication
  #  restart: unless-stopped    
