version: '3'
services:
  graphql-engine:
    container_name: graphql
    build:
      dockerfile: Dockerfile
      context: ./server/hasura
      args:
        - POSTGRES_URL=$POSTGRES_URL
        - HASURA_ADMIN_SECRET=$HASURA_ADMIN_SECRET
    ports:
    - "8081:8080"
    restart: always
  api:
    build:
      context: ./server/middle
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      #- OLLAMA_URL=http://51.158.62.147:11434
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./.env:/.env
      - ${DATA_ROOT_FOLDER:-/home/admin/data}:/app/data
  pdf-to-text:
    build:
      context: ./server/pdf_to_text
      dockerfile: Dockerfile
    container_name: pdf-to-text
    ports:
      - "3500:3500"
    volumes:
      - ${NSE_ANNOUNCEMENTS:-/home/admin/data/nse_announcements}:/app/input
      - ${NSE_ANNOUNCEMENTS:-/home/admin/data/nse_announcements}:/app/output
    environment:
      - PORT=3500
      - HOST=0.0.0.0
    restart: unless-stopped
  #ollama:
  #  image: ollama/ollama
  #  ports:
  #    - "11434:11434"
  #  volumes:
  #    - ${OLLAMA_MODELS:-/home/admin/data/ollama/ollama_models}:/root/.ollama/models