version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.local.nginx
    ports:
      - "80:80"
    volumes:
      - ./ui/dipsip-vuetify/dist:/usr/share/nginx/html
    depends_on:
      - api
  api:
    build:
      context: ./server/middle
      dockerfile: Dockerfile.local.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./sqlite_db:/app/sqlite_db  
      - ./server/middle/docker.env:/app/.env
      - ./server/downloads:/app/downloads     
