version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.local.nginx
    ports:
      - "80:80"
    volumes:
      - ./ui/dipsip-vuetify/dist:/usr/share/nginx/html
    depends_on:
      - api
  api:
    build:
      context: ./server/middle
      dockerfile: Dockerfile.local.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./sqlite_db:/app/sqlite_db  
      - ./server/middle/docker.env:/app/.env
      - ./server/downloads:/app/downloads
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ${SQLITE_DB:-/home/ec2-user/data/sqlite_db}:/data
    environment:
      - SQLITE_DATABASE=/data/dipsip.db  # Replace 'your_database.db' with your actual database filename
      - SQLITE_WEB_PASSWORD=dipsip_password       # Optional: set a password for basic authentication
      - SQLITE_WEB_USERNAME=admin_dipsip              # Optional: set a username for basic authentication
    depends_on:
      - api
    restart: unless-stopped     
