version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.local.nginx
    ports:
      - "80:80"
    volumes:
      - ./ui/dipsip-vuetify/dist:/usr/share/nginx/html
    depends_on:
      - api
  graphql-engine:
    container_name: graphql
    build:
      dockerfile: Dockerfile
      context: ./server/hasura
      args:
        - POSTGRES_URL=$POSTGRES_URL  
        - HASURA_ADMIN_SECRET=$HASURA_ADMIN_SECRET
    ports:
    - "8081:8080"
    restart: always
  api:
    build:
      context: ./server/middle
      dockerfile: Dockerfile.local.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ${SQLITE_DB:-/Users/sachetsingh1/telegram-mini-app/packages/data/sqlite_db}:/app/data/sqlite_db  
      - ./server/middle/docker.env:/app/.env
      - ./server/downloads:/app/downloads
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ${SQLITE_DB:-/home/ec2-user/data/sqlite_db}:/data
    environment:
      - SQLITE_DATABASE=/data/dipsip.db
      - SQLITE_WEB_PASSWORD=dipsip_password
      - SQLITE_WEB_USERNAME=admin_dipsip
    restart: unless-stopped

# Volumes definition at root level
volumes:
  postgres_data: